### ISSUE TITLE
Not working Androind in diffrent language

### ISSUE THREAD

**Issue by caglardurmus** [tttstudios/react-native-otp-input#61]
**Is your feature request related to a problem? Please describe.**
My Sms language is Turkish and sms is like:

> Mobile uygulama aktivasyonu icin dogrulama kodunuz: 12345 B001 

It's working on ios but it isn't on android.
When i use sms like "Code : 12345" it work on android. But i want to use it before i said. 

**Describe the solution you'd like**
We can change code text with some specific text.

**Comment by ericdao-ttt** [comment]
Hi @caglardurmus.

The flow should be like this: when user receive a message the phone will detect this message contains a code or not (usually with message has the word "code" or "passcode" in English) and shows the copy button. 
I think this problem is more related to the phone language setting.

Thank you!
